# Generated by Django 2.2.10 on 2020-03-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='descricao',
            field=models.TextField(default='Deveria colocar uma descrição sua aqui'),
        ),
    ]
