# Generated by Django 2.2.10 on 2020-03-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('titulo', models.CharField(max_length=50)),
                ('notas', models.TextField(max_length=8000)),
                ('data_publicacao', models.DateField(auto_now=True)),
                ('texto', models.TextField()),
            ],
            options={
                'verbose_name': 'Capitulo',
                'verbose_name_plural': 'Capitulos',
            },
        ),
    ]
